server:
  port: 8888
github:
  clientId: c41b232ed345a1741743
  redirectUri: http://localhost:8888/callback
  clientSecret: 21e3ed2eb3025f1503f73054461f9c73cfdd9079
#\u914D\u7F6Eh2\u6570\u636E\u7684\u6570\u636E\u6E90
spring:
  datasource:
    url: jdbc:h2:~/community
    username: sa
    password: 123
    driver-class-name: org.h2.Driver
